[package]
name = "billion_row_challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.7"
memmap2 = "0.9"
rustc-hash = "1.1"  # Faster HashMap

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[[bin]]
name = "billion_row_challange"
path = "src/main.rs"
