[package]
name = "billion_row_challange"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "billion_row_challange"
path = "src/main.rs"
